on:
  workflow_dispatch:

jobs:
  label_issue:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: "16.17"

    - name: Install Node.js dependencies
      run: yarn install

    - name: Build Project
      run: yarn build
